"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const appoimentsController_1 = require("../controllers/appoimentsController");
const auth_1 = require("../middlewares/auth");
const router = (0, express_1.Router)();
exports.router = router;
router.post('/create', auth_1.auth, appoimentsController_1.create);
router.post('/update/:id', auth_1.auth, appoimentsController_1.updateAppointmentById);
router.delete('/delete', auth_1.auth, appoimentsController_1.deleteAppointmentByUserId);
